#!/bin/tcsh -f

source ./build_i386
source ./build_armv6
source ./build_armv7


if (! -d lib) mkdir lib

rm lib/*.a


lipo -create -arch i386 i386/lib/libx264.a -arch armv6 armv6/lib/libx264.a -arch armv7 armv7/lib/libx264.a -output lib/libx264.a


cd lib
if (! -d include) mkdir include
cd incude
if (! -d x264) mkdir x264
cd ../..

cp armv7/include/* lib/include/x264/
