#!/bin/tcsh -f

source ./build_i386
source ./build_armv6
source ./build_armv7


if (! -d lib) mkdir lib

rm lib/*.a


lipo -create -arch i386 i386/lib/libavcodec.a -arch armv6 armv6/lib/libavcodec.a -arch armv7 armv7/lib/libavcodec.a -output lib/libavcodec.a
lipo -create -arch i386 i386/lib/libavdevice.a -arch armv6 armv6/lib/libavdevice.a -arch armv7 armv7/lib/libavdevice.a -output lib/libavdevice.a
lipo -create -arch i386 i386/lib/libavformat.a -arch armv6 armv6/lib/libavformat.a -arch armv7 armv7/lib/libavformat.a -output lib/libavformat.a
lipo -create -arch i386 i386/lib/libavutil.a -arch armv6 armv6/lib/libavutil.a -arch armv7 armv7/lib/libavutil.a -output lib/libavutil.a
lipo -create -arch i386 i386/lib/libswscale.a -arch armv6 armv6/lib/libswscale.a -arch armv7 armv7/lib/libswscale.a -output lib/libswscale.a


cp -r armv7/include lib/
