#!/bin/tcsh -f

if (! -d i386) mkdir i386

rm i386/*.a


export CROSS_COMPILE=/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/
export XCFLAGS="-isysroot /Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.0.sdk -I/Users/rcbt/Desktop/openssllib/include/ -arch i386"
export XLDFLAGS="-isysroot /Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.0.sdk -L/Users/rcbt/Desktop/openssllib/ -arch i386"


make SYS=darwin

make SYS=darwin prefix=i386/ install


make clean
